#!/usr/bin/env python3
Q=chr(39); D=chr(36); B=chr(92); lines=[]

def L(s):
    lines.append(s)

# Imports
L(f"import {Q}package:flutter/material.dart{Q};")
L(f"import {Q}package:provider/provider.dart{Q};")
L(f"import {Q}../providers/data_provider.dart{Q};")
L(f"import {Q}../models/vehicle.dart{Q};")
L(f"import {Q}../models/driver.dart{Q};")
L("")

# Class
L("class VehiclesScreen extends StatefulWidget {")
L("  const VehiclesScreen({super.key});")
L("  @override")
L("  State<VehiclesScreen> createState() => _VehiclesScreenState();")
L("}")
L("")
L("class _VehiclesScreenState extends State<VehiclesScreen>")
L("    with SingleTickerProviderStateMixin {")
L("  late final TabController _tabController;")
L("")
L("  @override")
L("  void initState() {")
L("    super.initState();")
L("    _tabController = TabController(length: 2, vsync: this);")
L("  }")
L("")
L("  @override")
L("  void dispose() {")
L("    _tabController.dispose();")
L("    super.dispose();")
L("  }")

# Vehicles tab
L("")
L("  Widget _buildVehiclesTab(DataProvider dp) {")
L("    final vehicles = dp.vehicles;")
L("    if (vehicles.isEmpty) {")
L("      return const Center(")
L(f"        child: Text({Q}\u041d\u0435\u0442 \u0430\u0432\u0442\u043e\u043c\u043e\u0431\u0438\u043b\u0435\u0439{Q},")
L("            style: TextStyle(fontSize: 16, color: Colors.grey)),")
L("      );")
L("    }")
L("    return ListView.builder(")
L("      padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),")
L("      itemCount: vehicles.length,")
L("      itemBuilder: (context, index) {")
L("        final v = vehicles[index];")
L("        return _buildVehicleCard(v, dp);")
L("      },")
L("    );")
L("  }")

L("")
L("  Widget _buildVehicleCard(Vehicle v, DataProvider dp) {")
L("    return Card(")
L("      margin: const EdgeInsets.only(bottom: 8),")
L("      child: InkWell(")
L("        borderRadius: BorderRadius.circular(12),")
L("        onTap: () => _editVehicleDialog(v, dp),")
L("        child: Padding(")
L("          padding: const EdgeInsets.all(14),")
L("          child: Row(")
L("            children: [")
L("              Expanded(")
L("                child: Column(")
L("                  crossAxisAlignment: CrossAxisAlignment.start,")
L("                  children: [")
L("                    Text(v.plateNumber,")
L("                        style: const TextStyle(")
L("                            fontSize: 17, fontWeight: FontWeight.bold)),")
L("                    const SizedBox(height: 4),")
L("                    Text(")
L(f"                      {Q}{D}{chr(123)}v.brand{chr(125)} {D}{chr(123)}v.model{chr(125)}{D}{chr(123)}v.year != null ? {Q} \u00b7 {D}{chr(123)}v.year{chr(125)}{Q} : {Q}{Q}{chr(125)}{Q},")
L("                      style: const TextStyle(fontSize: 14, color: Colors.grey),")
L("                    ),")
L("                  ],")
L("                ),")
L("              ),")
L("              Container(")
L("                padding:")
L("                    const EdgeInsets.symmetric(horizontal: 10, vertical: 5),")
L("                decoration: BoxDecoration(")
L("                  color: v.isActive")
L("                      ? const Color(0xFF2563EB).withOpacity(0.1)")
L("                      : Colors.grey.shade100,")
L("                  borderRadius: BorderRadius.circular(8),")
L("                ),")
L("                child: Row(")
L("                  mainAxisSize: MainAxisSize.min,")
L("                  children: [")
L("                    Container(")
L("                      width: 8,")
L("                      height: 8,")
L("                      decoration: BoxDecoration(")
L("                        shape: BoxShape.circle,")
L("                        color: v.isActive ? Colors.green : Colors.grey,")
L("                      ),")
L("                    ),")
L("                    const SizedBox(width: 6),")
L("                    Text(")
L(f"                      v.isActive ? {Q}\u0410\u043a\u0442\u0438\u0432\u0435\u043d{Q} : {Q}\u0421\u0432\u043e\u0431\u043e\u0434\u0435\u043d{Q},")
L("                      style: TextStyle(")
L("                        fontSize: 12,")
L("                        fontWeight: FontWeight.w600,")
L("                        color: v.isActive")
L("                            ? const Color(0xFF2563EB)")
L("                            : Colors.grey.shade700,")
L("                      ),")
L("                    ),")
L("                  ],")
L("                ),")
L("              ),")
L("            ],")
L("          ),")
L("        ),")
L("      ),")
L("    );")
L("  }")

# Add vehicle
L("")
L("  void _addVehicleDialog(DataProvider dp) {")
L("    _editVehicleDialog(null, dp);")
L("  }")

target = "/opt/CargoProfi/cargo_app/lib/screens/vehicles_screen.dart"
with open(target, "w", encoding="utf-8") as f:
    f.write(chr(10).join(lines) + chr(10))
print(f"Written {len(lines)} lines")
