openapi: "3.0.0"
info:
  title: Numino API
  version: "1.0.0"
paths:
  /ping:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ebe398cf4irb742g3f
      operationId: ping
  /{function}:
    get:
      parameters:
        - name: function
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ebe398cf4irb742g3f
      operationId: callGet
    post:
      parameters:
        - name: function
          in: path
          required: true
          schema:
            type: string
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ebe398cf4irb742g3f
      operationId: callPost
